name: paradrop-router
base: core20
version: "0.14"
summary: Paradrop wireless router
description: |
  Paradrop router is a configurable network router.

  Visit https://paradrop.org to learn more.

grade: stable
confinement: strict

apps:
  router:
    command: bin/router
    daemon: simple
    environment:
      UCI_CONFIG_DIR: $SNAP_DATA
    plugs:
      - firewall-control
      - hardware-observe
      - mount-observe
      - network
      - network-bind
      - network-control
      - process-control
      - system-observe

parts:
  router:
    plugin: python
    source: .
    stage-packages:
      - python3
    requirements:
      - requirements.txt

  dependencies:
    plugin: nil
    stage-packages:
      - haproxy
      - iw
      - parprouted
    filesets:
      binaries:
        - sbin/iw
        - usr/sbin/haproxy
        - usr/sbin/parprouted
      libraries:
        - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/liblua5.3.so.*
    stage:
      - $binaries
      - $libraries
    prime:
      - $binaries
      - $libraries

  # Build dnsmasq from the snappy team's source code because they implemented a
  # fix for failure under confinement. They removed code that tries to change
  # dnsmasq's running group.
  dnsmasq:
    plugin: make
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/wifi-ap
    source-type: git
    source-branch: dnsmasq/2.75
    build-packages:
      - build-essential
    make-parameters:
      - PREFIX=/
    organize:
      sbin/dnsmasq: bin/dnsmasq
    filesets:
      binaries:
        - bin/dnsmasq
    prime:
      - $binaries

  # Build hostapd from the snappy team's source code. This builds hostapd 2.6,
  # with some bug fixes, vulnerability patches, and support for the
  # no_probe_resp_if_max_sta option.
  hostapd:
    plugin: make
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/wifi-ap
    source-type: git
    source-branch: hostapd/2.6
    build-packages:
      - build-essential
      - pkg-config
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnl-route-3-dev
      - libssl-dev
    make-parameters:
      - BINDIR=/bin
    filesets:
      binaries:
        - bin/hostapd
        - bin/hostapd_cli
    prime:
      - $binaries
