name: paradrop-agent
version: 0.12.6
summary: Paradrop agent for managing an edge computing node
description: |
  The Paradrop agent manages hardware resources for an edge computing
  node and enables easy deployment of services to a virtualized runtime
  environment using Docker containers.

  Visit https://paradrop.org to learn more.

grade: stable
confinement: devmode

plugs:
  zerotier-control:
    interface: content
    target: $SNAP_COMMON

apps:
  paradrop:
    command: paradrop
    daemon: simple
    plugs:
      - account-control
      - docker
      - firewall-control
      - hardware-observe
        # I think we added kernel-module-control, not because we load kernel
        # modules but because of some other capability that is bundled with it.
        # However, it triggers manual review.
        # - kernel-module-control
      - network
      - network-bind
      - network-control
      - ppp
      - process-control
      - shutdown
        # Desired, but triggers manual review...
        # - snapd-control
      - system-observe

  pdlog:
    command: pdlog

hooks:
  configure:
    plugs: [network, network-control]

parts:
  localweb:
    plugin: dump
    source: paradrop/localweb

  pdlog:
    plugin: python
    python-version: python2
    source: paradrop/tools/pdlog

  paradrop:
    plugin: python
    python-version: python2
    source: paradrop/daemon
    build-packages:
      - python-dev
      - libffi-dev
    stage-packages:
      - libcurl4-openssl-dev
      - libpulse0
      - libssl-dev
      - python-openssl
      - python-pyasn1
      - python-pyasn1-modules
    organize:
      # For some reason, the libpulsecommon .so file could not be found in its
      # default install location, so move it to a place where it can be found.
      usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so: usr/lib/x86_64-linux-gnu/libpulsecommon-8.0.so

  dependencies:
    plugin: nil
    stage-packages:
      - dnsmasq
      - git
      - haproxy
      - iw
      - kmod
      - parprouted
      - systemd
    filesets:
      binaries:
        - bin/kmod
        - bin/systemctl
        - sbin/iw
        - sbin/modprobe
        - usr/bin/git
        - usr/sbin/dnsmasq
        - usr/sbin/haproxy
        - usr/sbin/parprouted
      libraries:
        - usr/lib/x86_64-linux-gnu/liblua5.3.so.*
    stage:
      - $binaries
      - $libraries
    prime:
      - $binaries
      - $libraries

  # This section exists because Ubuntu 16.04 is still distributing an old
  # version of hostapd (2.4), and there are changes in version 2.6 that we
  # would really like to have including bug fixes and support for the
  # no_probe_resp_if_max_sta option.
  #
  # We have compiled the hostapd 2.6 source code for the x86_64 architecture
  # and host a binary package at paradrop.org. When building an x86_64 snap
  # (common case), we will download and install those binaries. When building a
  # snap for other architectures, we still need hostapd, so we fall back to
  # using the distribution package (version 2.4, unfortunately).
  #
  # When hostapd 2.6 or higher becomes available as a distribution package, we
  # can remove this section entirely and simply add hostapd to the
  # stage-packages list and the binaries list in the "dependencies" part above.
  hostapd:
    plugin: dump
    source: https://paradrop.org/release/packages/hostapd-2.6.tar.bz2
    source-type: tar
    build-packages:
      - hostapd
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin

      # Depending on the build architecture, either copy our hostapd 2.6
      # binaries or use the binaries from the distribution package.
      if [ `arch` = "x86_64" ]; then
        echo "Using pre-built hostapd 2.6 binaries for x86_64..."
        cp -v hostapd hostapd_cli $SNAPCRAFT_PART_INSTALL/bin/
      else
        echo "Using hostapd distribution package..."
        cp -v /usr/sbin/hostapd $SNAPCRAFT_PART_INSTALL/bin/
        cp -v /usr/sbin/hostapd_cli $SNAPCRAFT_PART_INSTALL/bin/
      fi

      # Print the version of the hostapd binary installed.
      $SNAPCRAFT_PART_INSTALL/bin/hostapd -v || true
    organize:
      hostapd: bin/hostapd
      hostapd_cli: bin/hostapd_cli
    filesets:
      binaries:
        - bin/hostapd
        - bin/hostapd_cli
    stage:
      - $binaries
    prime:
      - $binaries
